alertmanager:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /alertmanager/$2
    ingressClassName: nginx
    hosts:
    - *
    paths:
    - /alertmanager(/|$)(.*)
  alertmanagerSpec:
    routePrefix: /alertmanager

grafana:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /grafana/$2
    ingressClassName: nginx
    hosts:
    - *
    path: /grafana(/|$)(.*)
  grafana.ini:
    security:
      cookie_secure: false
    server:
      domain: localhost
      protocol: http
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      serve_from_sub_path: true

prometheus:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /prometheus/$2
    ingressClassName: nginx
    hosts:
    - *
    paths:
    - /prometheus(/|$)(.*)
  prometheusSpec:
    externalUrl: /prometheus
    routePrefix: /prometheus
