# application specific
observability:
  enable: true
  alertmanager:
    ingress:
      enable: true
  grafana:
    ingress:
      enable: true
  prometheus:
    ingress:
      enable: true
    retention: 5d
    storage:
      class: local-path
      size: 10Gi

logging:
  enable: true

cloudflared:
  enable: true
  image:
    tag: 2023.5.1
  tunnelID: "69c38170-0ed1-42ea-b184-05cd40dced9c"
  ingress:
  - hostname: "k3d-laptop.buildaplatform.io"
