# application specific
observability:
  enable: true
  alertmanager:
    ingress:
      enable: true
  grafana:
    ingress:
      enable: true
  prometheus:
    ingress:
      enable: true
    retention: 5d
    storage:
      class: local-path
      size: 10Gi

logging:
  enable: true
