apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: networking
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.kubito.dev
    chart: cloudflared
    targetRevision: 1.0.2
    helm:
      values: |
        {{- .Values.cloudflared | toYaml | nindent 8 }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
