{{- if .Values.logging.enable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: observability
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    chart: loki-stack
    targetRevision: 2.9.10
    helm:
      values: |
        grafana:
          sidecar:
            datasources:
              enabled: false
        promtrail:
          initContainer:
          - name: init
            image: docker.io/busybox:1.33
            imagePullPolicy: IfNotPresent
            command:
              - sh
              - -c
              - sysctl -w fs.inotify.max_user_instances=128
            securityContext:
              privileged: true
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
