apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.6.1
    helm:
      values: |
        controller:
          kind: Deployment
          service:
            targetPorts:
              https: http
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              additionalLabels:
                release: "observability"
          nodeSelector:
            ingress-ready: "true"
          tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
            operator: Equal
          - effect: NoSchedule
            key: node-role.kubernetes.io/control-plane
            operator: Equal
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
