apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.6.1
    helm:
      valueFiles:
        - $repo/values/ingress-nginx/{{ .Values.ingress-nignx.valuesFile }}
  - repoURL: https://github.com/markandersontrocme/click-to-deploy
    targetRevision: feat/add-observability
    ref: repo
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
