apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: networking
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.kubito.dev
    chart: cloudflared
    targetRevision: 1.0.2
    helm:
      values: |
        image:
          tag: {{ .Values.cloudflared.image.tag }}
        tunnelID: {{ .Values.cloudflared.tunnelID | quote }}
        existingSecret: "tunnel-credentials"
        ingress:
        {{- range $ingress := .Values.cloudflared.ingress }}
        - name: {{ $ingress.hostname | quote }}
          service: "http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:443"
        {{- end }}
        - service: "http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:443"
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
