apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: extra-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/buildaplatform/gitops-kubernetes
    path: extra-resources
    targetRevision: feat/add-vault
    helm:
      parameters:
        - name: domain
          value: {{ .Values.domain }}
        - name: environment
          value: {{ .Values.environment }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
