redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 2
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: buildaplatform
    ingressClassName: nginx
    hosts:
      - argocd.local.buildaplatform.io
    tls:
      - secretName: argocd-server-tls
        hosts:
          - argocd.local.buildaplatform.io
    paths:
      - /

configs:
  params:
    "server.insecure": true

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicaCount: 2
