redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 2
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /argocd/$2
    ingressClassName: nginx
    paths:
    - /argocd(/|$)(.*)

configs:
  params:
    "server.insecure": true
    "server.rootpath": /argocd
    "server.basehref": /argocd

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicaCount: 2
