redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 2
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: buildaplatform
    ingressClassName: nginx
    hosts:
      - argocd.localdev.me
    tls:
      - secretName: argocd-localdev-me-cert
        hosts:
          - argocd.localdev.me
    paths:
      - /

configs:
  params:
    "server.insecure": true

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicaCount: 2
